[package]
name = "reminiscence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.37"
[target.'cfg(unix)'.dependencies]
x11rb = "0.13.0"
pulsectl-rs = "0.3.2"

